/* LUME V5.1 knowledge enhancement — interface unchanged. */
(function(){
'use strict';
badgeClass.mixed='b-both'; badgeLabel.mixed='LUME + Marriott';
const gxp={id:'gxp',title:'01A · GXP / Guest Experience',subtitle:'Cases, guest communication, Bonvoy context and handover',badge:'both',badgeText:'LUME + Marriott',intro:'Confirmed LUME Night: log into GXP at handover and use it for Night tasks assigned or handed over to you. The additional case/chat mechanics below come from LUME Front Office material and Marriott GXP guidance; exact Night ownership, response targets and property configuration follow current trainer/FOM instruction.',path:'EMPOWER: Guest Experiences (GXP) · authorized property access',steps:[
['Start of Night → GXP anmelden','[Confirmed LUME Night] Log into GXP during Spätdienst handover and keep it available for the night.','gxp login handover'],
['Review handed-over items','Understand which guest issues, Cases or Follow Ups are explicitly handed over to Night before continuing the audit sequence.','gxp cases handover'],
['Cases + guest requests','[LUME FO reference] Front Office regularly checks GXP for Cases, new Bonvoy arrivals and guest requests. At Night, act on items owned by your shift or handed over; do not invent a new monitoring frequency.','gxp cases guest requests'],
['Chat / CEC communication','[Marriott GXP guidance] New chats appear as notifications; CEC cases appear in “GXP Customer Care Open Cases”. Respond/route according to the current property process. No unconfirmed LUME Night response-time target is added here.','gxp chat cec customer care'],
['Follow Up status','[Marriott GXP guidance] Use Follow Up when further employee or manager action is still required. Reading a Case is not the same as resolving it.','gxp follow up'],
['Dispatch / Active status','[Marriott GXP guidance] GXP supports dispatch groups and Active/Inactive user status. Night Audit should not change property dispatch rules or admin configuration without authorization.','gxp dispatch active inactive'],
['Maintenance → Work Order','[Marriott GXP guidance] A Case can become a Work Order for maintenance tracking. Use only LUME’s configured workflow; Transcendent integration at this property remains to be confirmed locally.','gxp work order maintenance'],
['Bonvoy / Reviewed context','[LUME FO reference] Late Shift checks new Bonvoy arrivals and marks reviewed next-day arrivals as “Reviewed” after the arrival check. Night continues this only when handed over or required by current instruction; do not duplicate completed work blindly.','gxp bonvoy reviewed'],
['After EOD → %A136','[Confirmed LUME Night] Review HSK Traces and enter the relevant required items into GXP. Do not assume OPERA synchronized them automatically.','gxp a136 hsk traces'],
['Handover unresolved items','Leave unresolved Cases / Follow Ups visible and hand over status, owner and next action. Do not close an item only to clear the list.','gxp unresolved handover']
]};
if(!sections.some(s=>s.id==='gxp')){const i=sections.findIndex(s=>s.id==='start');sections.splice(i>=0?i+1:1,0,gxp)} phaseMap.gxp='START OF NIGHT';
const ctx={id:'context',title:'17 · LUME / Marriott Operating Context',subtitle:'Reference rules that help interpret Night decisions',badge:'both',badgeText:'Operational reference',intro:'Reference layer only. It makes the Control Center more informative but never overrides Checkliste Nachtdienst NEU, current live trainer instruction, Accounting/FOM approval or the exact OPERA workflow.',steps:[
['Exact PMS in use','LUME currently uses OPERA PMS Version 5.6.25.20, property FRANV. Do not use OPERA Cloud or OPERA Xpress navigation as the current LUME click path.','opera 5.6.25.20 franv'],
['Bonvoy recognition','Recognize Bonvoy membership in guest-facing arrival/check-in work and follow the current Marriott/LUME tier-benefit rules.','bonvoy recognition'],
['Marriott 15/5 service rule','Use the 15/5 service behavior for guest contact. It is not authorization for refunds, postings, points or compensation.','15 5 service'],
['Cashless transition','Project reference: LUME plans to become fully cashless from 01.10.2026. Until the cutover is implemented and confirmed, current cash controls remain operationally relevant. At transition, follow the newest FOM/Accounting instruction.','cashless october 2026'],
['Financial uncertainty = stop','For posting, refund, routing, settlement, adjustment, correction or unclear VCC coverage, do not guess. Confirm with trainer/FOM/Accounting.','financial stop']
]};
if(!sections.some(s=>s.id==='context')){const i=sections.findIndex(s=>s.id==='open');sections.splice(i>=0?i+1:sections.length,0,ctx)} phaseMap.context='REFERENCE';
const cards=[
{id:'gxpnight',title:'GXP during Night Audit',code:'GXP',sectionId:'gxp',status:'mixed',aliases:['gxp','empower gxp','gxp night','gxp cases','bonvoy gxp','how do i use gxp','si perdor gxp','wie nutze ich gxp'],keywords:'gxp cases chat cec follow up dispatch bonvoy reviewed a136 hsk handover guest requests',summary:'At LUME Night Audit, GXP is part of handover and guest-experience follow-up. Log in at shift takeover, work Night-owned / handed-over items, and after EOD enter the relevant %A136 HSK Traces into GXP. Marriott guidance explains case/chat/CEC/Follow Up mechanics but does not create new LUME Night ownership by itself.',path:'EMPOWER: Guest Experiences (GXP) · authorized property access',steps:['Log into GXP during Spätdienst handover.','Review open items handed over to Night and guest communication that requires action during your shift.','For a Case, verify issue, owner/current status and next action before changing status.','For chat/CEC, respond or route according to the current property/Marriott process.','Use Follow Up when more employee/manager action is required.','For maintenance, use Work Order only through the configured property process.','Treat Bonvoy “Reviewed” handling as Front Office context; continue it at Night only when handed over / required.','After EOD, enter relevant %A136 HSK Traces into GXP.','Hand over unresolved Cases / Follow Ups clearly instead of closing them to clear the list.'],checks:['Case status reflects reality; unresolved items have a clear owner/next action.'],stop:['Do not change GXP admin/dispatch configuration, promise compensation or close unresolved Cases without authority.']},
{id:'gxpcec',title:'GXP · CEC Case',code:'CEC',sectionId:'gxp',status:'mixed',aliases:['cec','cec case','gxp customer care open cases','customer care open cases'],keywords:'gxp cec customer care open cases case takeover respond escalate',summary:'Marriott GXP guidance places CEC cases in “GXP Customer Care Open Cases”. Follow the current property / Marriott Case Takeover process when the case belongs to Night.',path:'GXP → GXP Customer Care Open Cases',steps:['Read the full Case/context.','Confirm whether Night owns it or it needs dispatch/escalation.','Respond or route through the current property process.','Use Follow Up when further action remains.','Hand over unresolved ownership/next action.'],checks:['CEC Case is not left unowned when Night is the designated owner.'],stop:['Do not invent compensation or a LUME-specific response-time promise.']},
{id:'gxpworkorder',title:'GXP · Case vs Work Order',code:'Work Order',sectionId:'gxp',status:'mixed',aliases:['work order','gxp work order','maintenance case'],keywords:'gxp work order maintenance engineering transcendent',summary:'GXP supports Work Orders for maintenance tracking. Use the property-configured workflow only; LUME’s exact Transcendent integration status is not confirmed here.',path:'GXP Case → Work Order (when applicable)',steps:['Confirm it is a maintenance/engineering issue.','Use the current LUME-configured Case/Work Order process.','Route to the responsible function when authorized.','Keep guest-facing Case status and handover aligned with actual repair progress.'],checks:['Issue remains traceable until repair/follow-up is complete.'],stop:['Do not assume an integration or recurring Work Order setup not confirmed for LUME.']},
{id:'operaversion',title:'Current LUME PMS',code:'OPERA 5.6.25.20',sectionId:'context',status:'mixed',aliases:['opera version','which opera','opera cloud','opera xpress','franv'],keywords:'opera pms 5.6.25.20 franv cloud xpress',summary:'Current confirmed LUME system: OPERA PMS Version 5.6.25.20, property FRANV. Cloud/Xpress instructions are not current LUME click paths.',path:'OPERA PMS 5.6.25.20 · FRANV',steps:['Use the OPERA 5.6.25.20 paths in this Control Center.','After a future Cloud migration, build a separate confirmed workflow from the new live screens.'],checks:['Live system/version matches the procedure.'],stop:['Do not mix OPERA Cloud/Xpress navigation into the current SOP.']},
{id:'cashlesscontext',title:'LUME cashless transition',code:'01.10.2026',sectionId:'context',status:'mixed',aliases:['cashless','01.10.2026','1 october 2026'],keywords:'lume cashless transition october 2026 cash kasse',summary:'Project reference: LUME plans to become fully cashless from 01.10.2026. Until management confirms the cutover is active, current cash-count/Kassenabmeldung workflow remains relevant.',path:'Operational transition · newest FOM / Accounting instruction wins',steps:['Before cutover, follow current cash controls.','At/after cutover, confirm the newest LUME instruction before removing cash-related Night steps.'],checks:['Procedure matches the live operating date and current management instruction.'],stop:['Do not skip cash controls early just because the future date is known.']},
{id:'service155',title:'Marriott 15/5 service rule',code:'15/5',sectionId:'context',status:'mixed',aliases:['15/5','15 5 rule','marriott 15/5'],keywords:'marriott service guest recognition 15 5',summary:'Use the 15/5 rule as guest-facing service behavior. It does not authorize a financial action.',path:'Guest-facing service behavior',steps:['Apply the current LUME/Marriott 15/5 behavior naturally.','For compensation, refunds, points or postings, follow the separate authorization rule.'],checks:['Service behavior and financial authority are not confused.'],stop:['15/5 is not authorization for compensation or posting changes.']}
];
cards.forEach(c=>{if(!qaCards.some(x=>x.id===c.id))qaCards.push(c);if(!allCards.some(x=>x.id===c.id))allCards.push(c)});if(!codes.some(x=>x[0]==='GXP'))codes.push(['GXP','Cases / guest communication / CEC / Follow Up']);
const gr=guidedRun.find(s=>/GXP anmelden/i.test(s.title||''));if(gr){gr.answerId='gxpnight';delete gr.sectionId;gr.source='both';gr.detail='Receive Spätdienst handover and log into GXP. Work only Night-owned / handed-over items; use HOW for LUME + Marriott GXP logic.'}
const oldIntent=intentCard;intentCard=function(raw){const q=norm(raw);if(q==='gxp'||q.includes('gxp night')||q.includes('empower gxp'))return allCards.find(c=>c.id==='gxpnight');if(q==='cec'||q.includes('cec case')||q.includes('customer care open cases'))return allCards.find(c=>c.id==='gxpcec');if((q.includes('gxp')||q.includes('case'))&&q.includes('work order'))return allCards.find(c=>c.id==='gxpworkorder');if(q.includes('opera')&&(q.includes('version')||q.includes('cloud')||q.includes('xpress')||q.includes('franv')))return allCards.find(c=>c.id==='operaversion');if(q.includes('cashless')||q.includes('01.10.2026'))return allCards.find(c=>c.id==='cashlesscontext');if(q.includes('15/5')||q.includes('15 5'))return allCards.find(c=>c.id==='service155');return oldIntent(raw)};
})();