/* LUME V5.1 exact SOP-linked visuals — interface unchanged. */
(function(){
'use strict';
const map={trace:[['vg-start',[1]]],pm:[['vg-pmextend',[0,1,2]]],cover:[['vg-cover',[0,1,2,3,4]]],ps101:[['vg-cover',[0]]],minibar:[['vg-minibar',[0,1,2,3]]],d140cc:[['vg-d140cc',[0,1,2,3,4]]],d140storno:[['vg-d140storno',[0]]],eodstart:[['vg-eod',[0,1,2]]],e100:[['vg-e100',[0,1]]],t122:[['vg-t122',[0]]],p112:[['vg-p112',[0]]],r118:[['vg-r118',[0]]],vcc:[['vg-vcc',[0]]],email:[['vg-email',[0,1]]],kassenschnittmail:[['vg-email',[0,1]]],minibar_section:[['vg-minibar',[0,1,2,3]]],cover_section:[['vg-cover',[0,1,2,3,4]]],cc_section:[['vg-d140cc',[0,1,2,3,4]]],eod_section:[['vg-eod',[0,1,2]]],reports_section:[['vg-e100',[0,1]],['vg-t122',[0]],['vg-p112',[0]]],r118_section:[['vg-r118',[0]]],vcc_section:[['vg-vcc',[0]]],email_section:[['vg-email',[0,1]]]};
const sec={minibar:'minibar_section',cover:'cover_section',cc:'cc_section',eod:'eod_section',reports:'reports_section',r118:'r118_section',vcc:'vcc_section',email:'email_section'};
const ent=r=>map[map[r]?r:(sec[r]||r)]||[];const byId=id=>visualGuides.find(g=>g.id===id);
function items(r){const o=[];ent(r).forEach(([id,ix])=>{const g=byId(id);if(g)ix.forEach(i=>{if(g.images[i])o.push({g:g,im:g.images[i]})})});return o}
function guides(r){const s=new Set(),o=[];ent(r).forEach(([id])=>{const g=byId(id);if(g&&!s.has(id)){s.add(id);o.push(g)}});return o}
getVisualGuidesForRef=function(r){return guides(r)};
function openExact(r,title){const a=items(r);if(!a.length)return;const d=document.getElementById('drawer'),h=document.getElementById('drawerContent');let x='<h2>'+esc(title||a[0].g.title)+'</h2><p class="muted" style="margin-top:6px">Only the screenshot(s) linked to this SOP / workflow are shown here.</p><div class="visualgallery" style="padding:14px 0">';a.forEach((z,i)=>x+='<figure class="figure"><img src="'+z.im.src+'" alt="'+esc(z.im.caption)+'" loading="lazy" onclick="openImageZoom(this.src,this.alt)"><figcaption><b>'+(i+1)+'.</b> '+esc(z.im.caption)+'</figcaption></figure>');h.innerHTML=x+'</div>';d.classList.add('show');document.body.style.overflow='hidden'}
openVisualForRef=function(r){openExact(r)};
openVisualGuide=function(id){const g=byId(id);if(!g)return;const r=Object.keys(map).find(k=>map[k].some(x=>x[0]===id));if(r)return openExact(r,g.title);const d=document.getElementById('drawer'),h=document.getElementById('drawerContent');let x='<h2>'+esc(g.title)+'</h2><p class="muted" style="margin-top:6px">'+esc(g.summary||'')+'</p><div class="visualgallery" style="padding:14px 0">';(g.images||[]).forEach((im,i)=>x+='<figure class="figure"><img src="'+im.src+'" alt="'+esc(im.caption)+'" loading="lazy" onclick="openImageZoom(this.src,this.alt)"><figcaption><b>'+(i+1)+'.</b> '+esc(im.caption)+'</figcaption></figure>');h.innerHTML=x+'</div>';d.classList.add('show');document.body.style.overflow='hidden'};
renderInlineVisuals=function(r){const a=items(r);if(!a.length)return '';let x='<div class="visualinline"><b>Visual help · linked to this workflow</b><div class="inlinebtns"><button class="btn" onclick="openVisualForRef(\''+String(r).replace(/'/g,"\\'")+'\')">SEE linked screenshots</button></div><div class="inline-mini">';a.slice(0,2).forEach(z=>x+='<img src="'+z.im.src+'" alt="'+esc(z.im.caption)+'" onclick="openImageZoom(this.src,this.alt)" title="Click to zoom">');return x+'</div></div>'};
const a=byId('vg-start');if(a)a.refIds=['trace'];const b=byId('vg-hsk');if(b)b.refIds=[];
})();